# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a142e3e4fcf4d3dba2f3d292e21c39061ef2de8534d5c8c4059a03ee8a08b9c0107235e234786787aed314df281634ff5da9ce8375e17f959b38af0186c7574

test:
  secret_key_base: f6709e6e9f71ca521166f6ea82dc12d78bb25f1600e49da47d6153657dd26082faaf6e7e101fc5d5b8b7bb36758a159d779e7d2ed6361c844a41d0dfce51591c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
